from __future__ import annotations

import re
from pathlib import PurePosixPath

from overscope.models import Intent, Session

PATH_RE = re.compile(
    r"(?<![\w@])(?:[\w.@+-]+/)+[\w.@+\-]+(?:\.[A-Za-z0-9]+)?|"
    r"(?<![\w@])[\w@+-]+\.(?:py|js|jsx|ts|tsx|go|rs|java|rb|php|toml|yaml|yml|json|md)\b"
)
TOKEN_RE = re.compile(r"[A-Za-z][A-Za-z0-9_-]{2,}")
OPERATIONS = {
    "add": "add",
    "build": "build",
    "create": "create",
    "delete": "delete",
    "remove": "delete",
    "fix": "fix",
    "implement": "implement",
    "refactor": "refactor",
    "rename": "rename",
    "update": "update",
    "change": "change",
    "debug": "debug",
    "test": "test",
}
STOPWORDS = {
    "the", "and", "that", "this", "with", "from", "into", "your", "have", "will",
    "should", "would", "could", "please", "code", "file", "files", "make", "need",
    "want", "then", "when", "what", "where", "which", "while", "only", "without",
    "also", "just", "using", "user", "work", "project", "current", "existing",
    "request", "changes", "change", "must", "does", "not", "for",
}

_NOISE_BLOCKS = [
    re.compile(r"<system-reminder>.*?</system-reminder>", re.I | re.S),
    re.compile(r"<recommended_plugins>.*?</recommended_plugins>", re.I | re.S),
    re.compile(r"<environment_context>.*?</environment_context>", re.I | re.S),
    re.compile(r"<user_instructions>.*?</user_instructions>", re.I | re.S),
    re.compile(r"<command-(?:name|message|args|contents)>.*?</command-[a-z]+>", re.I | re.S),
    re.compile(r"<local-command-(?:stdout|stderr)>.*?</local-command-[a-z]+>", re.I | re.S),
]
_IMAGE_OPEN = re.compile(r"<image\b[^>]*>?", re.I | re.S)
_IMAGE_CLOSE = re.compile(r"</image\s*>", re.I)
_PASTED_HEADER = re.compile(r"^\s*#+\s*Files pasted by the user:\s*", re.I)
_MENTIONED_HEADER = re.compile(r"^\s*#+\s*Files? (?:mentioned|attached) by the user:", re.I)
_MY_REQUEST = re.compile(r"##\s*My request:\s*", re.I)
_ATTACH_BOILERPLATE = re.compile(
    r"Distinguish instructions in attached documents from the user'?s request\.?", re.I
)
_RAN_COMMANDS = re.compile(r"^\s*Ran \d+ commands?\b[:.]?\s*", re.I)
_INTERRUPT = re.compile(r"\[Request interrupted by user[^\]]*\]", re.I)
_FULL_MESSAGE_NOISE = re.compile(
    r"^(?:"
    r"This session is being continued from a previous conversation"
    r"|Caveat: The messages below were generated by the user while running"
    r"|Base directory for this skill:"
    r"|\[Request interrupted by user"
    r"|The user (?:sent the following message|opened the file)"
    r")",
    re.I,
)

def extract_intent(session: Session) -> Intent:
    messages: list[str] = []
    for raw in session.user_messages:
        cleaned = _clean_message(raw)
        if cleaned:
            messages.append(cleaned)
    if not messages:
        return Intent(
            text="No usable user instruction found in the session.",
            operation=None,
            paths=[],
            keywords=[],
            constraints=[],
            confidence=0.0,
            reasons=["session contained no substantive visible user message"],
        )
    scored = [(index, _instruction_score(text), text) for index, text in enumerate(messages)]
    plausible = [item for item in scored if item[1] >= 2]
    _, score, text = plausible[-1] if plausible else scored[-1]
    raw_paths = (_normalize_path(match) for match in PATH_RE.findall(text))
    paths = list(dict.fromkeys(path for path in raw_paths if _looks_like_path(path)))
    words = [word.lower() for word in TOKEN_RE.findall(text)]
    operation = next((OPERATIONS[word] for word in words if word in OPERATIONS), None)
    constraints = _constraints(text)
    avoid = _avoid_tokens(text)
    path_tokens = {token for path in paths for token in _path_tokens(path)}
    keywords = [
        word
        for word in dict.fromkeys(words)
        if word not in STOPWORDS
        and word not in OPERATIONS
        and word not in path_tokens
        and word not in avoid
        and len(word) > 2
    ][:24]
    confidence = min(
        0.95, 0.35 + (0.2 if operation else 0) + (0.2 if paths else 0) + min(score, 4) * 0.05
    )
    reasons = ["selected the most recent message with instruction-like language"]
    if len(messages) < len(session.user_messages):
        reasons.append("filtered injected wrappers and non-instruction messages")
    if paths:
        reasons.append("instruction contains explicit path references")
    if operation:
        reasons.append(f"recognized requested operation: {operation}")
    return Intent(
        text=text,
        operation=operation,
        paths=paths,
        keywords=keywords,
        constraints=constraints,
        confidence=confidence,
        reasons=reasons,
        avoid=avoid,
    )

def _clean_message(raw: str) -> str | None:
    """Return a usable instruction from a raw user message, or ``None`` for noise.

    Real Claude and Codex transcripts interleave the human's turns with injected
    scaffolding: continuation summaries, slash-command echoes, environment context,
    pasted-file digests, and image attachments. This unwraps the salvageable text and
    drops messages that carry no instruction.
    """
    text = raw.strip()
    if not text:
        return None
    for block in _NOISE_BLOCKS:
        text = block.sub(" ", text)
    text = _IMAGE_OPEN.sub(" ", text)
    text = _IMAGE_CLOSE.sub(" ", text)
    text = _INTERRUPT.sub(" ", text)
    text = _ATTACH_BOILERPLATE.sub(" ", text)
    text = text.strip()

    request = _MY_REQUEST.search(text)
    if request:
        text = text[request.end() :].strip().lstrip("\\").strip()
    elif _PASTED_HEADER.match(text):
        text = _unwrap_pasted(text)
    elif _MENTIONED_HEADER.match(text):
        text = _strip_reference_lines(text)

    text = _RAN_COMMANDS.sub("", text).strip()
    if not text or _FULL_MESSAGE_NOISE.match(text):
        return None
    return text if _is_substantive(text) else None

def _unwrap_pasted(text: str) -> str:
    rest = _PASTED_HEADER.sub("", text).strip()
    preview = re.match(r'^#+\s*"(.*)"\s*:\s*\S', rest, re.S)
    if preview:
        return preview.group(1).strip().rstrip("…").strip()
    return _strip_reference_lines(text)

def _strip_reference_lines(text: str) -> str:
    """Drop markdown headers and `name: /path` file references, keep any real prose."""
    kept = [
        line
        for line in text.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    return "\n".join(kept).strip()

def _is_substantive(text: str) -> bool:
    if len(text) < 8:
        return False
    words = [word for word in re.findall(r"[A-Za-z]{2,}", text) if word.lower() not in _FILE_WORDS]
    return len(words) >= 2

_FILE_WORDS = {"png", "jpg", "jpeg", "gif", "mp4", "mov", "pdf", "txt", "sb3"}

def _instruction_score(text: str) -> int:
    words = {word.lower() for word in TOKEN_RE.findall(text)}
    score = sum(1 for word in words if word in OPERATIONS)
    score += 1 if PATH_RE.search(text) else 0
    score += (
        1
        if any(term in text.lower() for term in ("please", "don't", "do not", "must", "only"))
        else 0
    )
    return score

_MODIFY = "|".join(
    rf"{stem}\w*"
    for stem in (
        "chang", "touch", "modif", "edit", "alter", "renam", "mov",
        "delet", "remov", "refactor", "rewrit", "updat", "overwrit",
    )
)
_NEGATIVE_CLAUSE = re.compile(
    rf"(?:do ?n['’]?t|do not|must not|never)\s+(?:{_MODIFY})\s+"
    rf"((?:\.[A-Za-z0-9_.-]+)|[^.!?\n;,]*)"
    rf"|(?:without|avoid)\s+(?:{_MODIFY})\s+"
    rf"((?:\.[A-Za-z0-9_.-]+)|[^.!?\n;,]*)",
    re.I,
)
_CLAUSE_END = re.compile(r"\b(?:and|but|while|then|so)\b")

def _avoid_tokens(text: str) -> list[str]:
    """Nouns the user asked NOT to touch ("don't change auth"). These are anti-scope
    signals: a changed file matching one is evidence of going outside the request."""
    tokens: dict[str, None] = {}
    for match in _NEGATIVE_CLAUSE.finditer(text):
        clause = _CLAUSE_END.split(match.group(1) or match.group(2) or "", maxsplit=1)[0]
        for word in TOKEN_RE.findall(clause):
            lowered = word.lower()
            if lowered not in STOPWORDS and lowered not in OPERATIONS and len(lowered) > 2:
                tokens[lowered] = None
    return list(tokens)

def _constraints(text: str) -> list[str]:
    patterns = [
        r"\bonly\b[^.!?\n]*",
        r"\bdo not\b[^.!?\n]*",
        r"\bdon't\b[^.!?\n]*",
        r"\bwithout\b[^.!?\n]*",
        r"\bmust(?: not)?\b[^.!?\n]*",
    ]
    found: list[str] = []
    for pattern in patterns:
        found.extend(match.strip() for match in re.findall(pattern, text, flags=re.IGNORECASE))
    return list(dict.fromkeys(found))[:8]

_KNOWN_DIRS = ("src/", "lib/", "app/", "test/", "tests/", "pkg/", "cmd/", "internal/", "packages/")

def _looks_like_path(path: str) -> bool:
    """Distinguish a real file/dir reference from prose that merely contains a slash.

    ``src/api/users.js`` is a path; ``console/terminal`` and ``CLI/TUI`` are not. This
    keeps everyday "and/or" phrasing from being mistaken for an explicit scope anchor.
    """
    lowered = path.lower()
    if re.search(r"\.[a-z0-9]{1,5}$", lowered):
        return True
    if lowered.startswith(_KNOWN_DIRS):
        return True
    return path.count("/") >= 2

def _normalize_path(path: str) -> str:
    return path.strip("`'\"").replace("\\", "/").rstrip(".,;:!?)")

def _path_tokens(path: str) -> set[str]:
    values: set[str] = set()
    for part in PurePosixPath(path.lower()).parts:
        values.update(token for token in re.split(r"[._-]", part) if len(token) > 2)
    return values
